/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 6:33:27 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

 

@class UILabel, _UILegibilityView, NSString, UIFont, NSAttributedString, UIColor, _UILegibilitySettings;

@interface SBUILegibilityLabel : UIView <SBUILegibility> {

	UILabel* _lookasideLabel;
	_UILegibilityView* _legibilityView;
	BOOL _isDirty;
	double _strength;
	long long _options;
	double _scale;
	NSString* _string;
	UIFont* _font;
	NSAttributedString* _attributedText;
	UIColor* _textColorOverride;
	_UILegibilitySettings* _legibilitySettings;
	BOOL _isWaitingToMoveToWindow;

}

@property (nonatomic,copy) NSAttributedString * attributedText;                       //@synthesize attributedText=_attributedText - In the implementation block
@property (nonatomic,copy) NSString * string;                                         //@synthesize string=_string - In the implementation block
@property (nonatomic,copy) UIColor * textColor; 
@property (nonatomic,retain) UIFont * font;                                           //@synthesize font=_font - In the implementation block
@property (assign,nonatomic) long long numberOfLines; 
@property (assign,nonatomic) BOOL adjustsFontSizeToFitWidth; 
@property (assign,nonatomic) double minimumScaleFactor; 
@property (assign,nonatomic) long long textAlignment; 
@property (assign,nonatomic) long long lineBreakMode; 
@property (assign,nonatomic) float hyphenationFactor; 
@property (nonatomic,readonly) UIEdgeInsets characterOverflowInsets; 
@property (nonatomic,readonly) double firstBaselineOffsetFromBottom; 
@property (nonatomic,readonly) double lastBaselineOffsetFromBottom; 
@property (nonatomic,readonly) double baselineOffset; 
@property (assign,nonatomic) double strength;                                         //@synthesize strength=_strength - In the implementation block
@property (nonatomic,retain) _UILegibilitySettings * legibilitySettings;              //@synthesize legibilitySettings=_legibilitySettings - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setFont:(UIFont *)arg1 ;
-(CGSize)intrinsicContentSize;
-(id)viewForFirstBaselineLayout;
-(void)layoutSubviews;
-(void)setMinimumScaleFactor:(double)arg1 ;
-(NSAttributedString *)attributedText;
-(NSString *)string;
-(id)viewForLastBaselineLayout;
-(float)hyphenationFactor;
-(void)setHyphenationFactor:(float)arg1 ;
-(void)_intrinsicContentSizeInvalidatedForChildView:(id)arg1 ;
-(void)_markOurselfDirty;
-(long long)lineBreakMode;
-(void)_updateLabelForLegibilitySettings;
-(void)setTextAlignment:(long long)arg1 ;
-(id)initWithSettings:(id)arg1 strength:(double)arg2 string:(id)arg3 font:(id)arg4 ;
-(long long)numberOfLines;
-(id)initWithSettings:(id)arg1 strength:(double)arg2 string:(id)arg3 font:(id)arg4 options:(long long)arg5 ;
-(void)setString:(NSString *)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(double)lastBaselineOffsetFromBottom;
-(void)setBounds:(CGRect)arg1 ;
-(void)setLegibilitySettings:(_UILegibilitySettings *)arg1 ;
-(void)setStrength:(double)arg1 ;
-(double)baselineOffset;
-(BOOL)_needsColorImage;
-(void)setLineBreakMode:(long long)arg1 ;
-(void)setAttributedText:(NSAttributedString *)arg1 ;
-(double)minimumScaleFactor;
-(id)initWithCoder:(id)arg1 ;
-(void)setOptions:(long long)arg1 ;
-(void)setNumberOfLines:(long long)arg1 ;
-(double)strength;
-(id)initWithSettings:(id)arg1 strength:(double)arg2 ;
-(_UILegibilitySettings *)legibilitySettings;
-(void)setTextColor:(UIColor *)arg1 ;
-(UIFont *)font;
-(void)didMoveToWindow;
-(BOOL)adjustsFontSizeToFitWidth;
-(UIColor *)textColor;
-(UIEdgeInsets)characterOverflowInsets;
-(double)firstBaselineOffsetFromBottom;
-(long long)textAlignment;
-(void)setAdjustsFontSizeToFitWidth:(BOOL)arg1 ;
-(void)_updateLegibilityView;
@end

